services:
  web:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run prisma generate deploy && npm run prisma migrate deploy && npm run dev"
    environment:
      NODE_ENV: development

volumes:
  node_modules:
