// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma/orm-postgres/adapter/operation-types";
import type {
	Contract as ContractType,
	ExecutionHashBase,
	NamespaceId,
	ProfileHashBase,
	StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

import type {
	ContractWithTypeMaps,
	TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
	Bit,
	Char,
	Interval,
	JsonValue,
	Numeric,
	CodecTypes as PgTypes,
	Time,
	TimeString,
	Timestamp,
	TimestampString,
	Timestamptz,
	TimestamptzString,
	Timetz,
	VarBit,
	Varchar,
} from "@prisma/orm-postgres/target/codec-types";

export type StorageHash =
	StorageHashBase<"993eb526e23f91fcffd3f2f8d13b6b5d951d692c5775a75bbfb4a7936b872696">;
export type ExecutionHash =
	ExecutionHashBase<"f913d88f21793641ed495ae74edd64b5a3eb809374429fb18045c1bc17ed4e9d">;
export type ProfileHash =
	ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
	readonly avg: {
		readonly byCodec: {
			readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/float4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/int2@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/int4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/int8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/int8number@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/unboundedint@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "sql/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
		};
	};
	readonly avgDecimal: {
		readonly byCodec: {
			readonly "pg/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/int2@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/int4@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/int8@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/int8number@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/unboundedint@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "sql/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
		};
	};
	readonly count: {
		readonly byCodec: {};
		readonly withoutInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
		readonly anyInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
	};
	readonly countBigInt: {
		readonly byCodec: {};
		readonly withoutInput: { readonly output: "pg/int8@1"; readonly nullable: false };
		readonly anyInput: { readonly output: "pg/int8@1"; readonly nullable: false };
	};
	readonly max: {
		readonly byCodec: {
			readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
			readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
			readonly "pg/date-temporal@1": {
				readonly output: "pg/date-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
			readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
			readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
			readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
			readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
			readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
			readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
			readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
			readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
			readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
			readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
			readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
			readonly "pg/time-temporal@1": {
				readonly output: "pg/time-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/timestamp-string@1": {
				readonly output: "pg/timestamp-string@1";
				readonly nullable: true;
			};
			readonly "pg/timestamp-temporal@1": {
				readonly output: "pg/timestamp-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/timestamptz-string@1": {
				readonly output: "pg/timestamptz-string@1";
				readonly nullable: true;
			};
			readonly "pg/timestamptz-temporal@1": {
				readonly output: "pg/timestamptz-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
			readonly "pg/unboundedint@1": {
				readonly output: "pg/unboundedint@1";
				readonly nullable: true;
			};
			readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
			readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
			readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
			readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
			readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
			readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
		};
	};
	readonly min: {
		readonly byCodec: {
			readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
			readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
			readonly "pg/date-temporal@1": {
				readonly output: "pg/date-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
			readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
			readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
			readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
			readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
			readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
			readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
			readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
			readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
			readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
			readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
			readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
			readonly "pg/time-temporal@1": {
				readonly output: "pg/time-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/timestamp-string@1": {
				readonly output: "pg/timestamp-string@1";
				readonly nullable: true;
			};
			readonly "pg/timestamp-temporal@1": {
				readonly output: "pg/timestamp-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/timestamptz-string@1": {
				readonly output: "pg/timestamptz-string@1";
				readonly nullable: true;
			};
			readonly "pg/timestamptz-temporal@1": {
				readonly output: "pg/timestamptz-temporal@1";
				readonly nullable: true;
			};
			readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
			readonly "pg/unboundedint@1": {
				readonly output: "pg/unboundedint@1";
				readonly nullable: true;
			};
			readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
			readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
			readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
			readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
			readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
			readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
		};
	};
	readonly sum: {
		readonly byCodec: {
			readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
			readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "pg/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
			readonly "pg/int2@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
			readonly "pg/int4@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
			readonly "pg/int8@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
			readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
			readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
			readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
			readonly "pg/unboundedint@1": {
				readonly output: "pg/unboundedint@1";
				readonly nullable: true;
			};
			readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
			readonly "sql/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
		};
	};
	readonly sumBigInt: {
		readonly byCodec: {
			readonly "pg/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
			readonly "pg/int2@1": { readonly output: "pg/int8@1"; readonly nullable: true };
			readonly "pg/int4@1": { readonly output: "pg/int8@1"; readonly nullable: true };
			readonly "pg/int8@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
			readonly "pg/int8number@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
			readonly "pg/unboundedint@1": {
				readonly output: "pg/unboundedint@1";
				readonly nullable: true;
			};
			readonly "sql/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
		};
	};
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
	? Encoded extends CodecTypes[CodecId]["json"]
		? Encoded
		: CodecTypes[CodecId]["json"]
	: Encoded;

export type FieldOutputTypes = {
	readonly public: {
		readonly Account: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly issuer: CodecTypes["pg/text@1"]["output"];
			readonly accountId: CodecTypes["pg/text@1"]["output"];
			readonly providerId: CodecTypes["pg/text@1"]["output"];
			readonly userId: CodecTypes["pg/uuid@1"]["output"];
			readonly accessToken: CodecTypes["pg/text@1"]["output"] | null;
			readonly refreshToken: CodecTypes["pg/text@1"]["output"] | null;
			readonly idToken: CodecTypes["pg/text@1"]["output"] | null;
			readonly accessTokenExpiresAt: CodecTypes["pg/timestamp-temporal@1"]["output"] | null;
			readonly refreshTokenExpiresAt: CodecTypes["pg/timestamp-temporal@1"]["output"] | null;
			readonly scope: CodecTypes["pg/text@1"]["output"] | null;
			readonly password: CodecTypes["pg/text@1"]["output"] | null;
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly ChatInterrupt: {
			readonly interruptId: CodecTypes["pg/text@1"]["output"];
			readonly runId: CodecTypes["pg/text@1"]["output"];
			readonly threadId: CodecTypes["pg/text@1"]["output"];
			readonly status: CodecTypes["pg/text@1"]["output"];
			readonly requestedAt: CodecTypes["pg/int8@1"]["output"];
			readonly resolvedAt: CodecTypes["pg/int8@1"]["output"] | null;
			readonly payload: CodecTypes["pg/jsonb@1"]["output"];
			readonly response: CodecTypes["pg/jsonb@1"]["output"] | null;
		};
		readonly ChatRun: {
			readonly runId: CodecTypes["pg/text@1"]["output"];
			readonly threadId: CodecTypes["pg/text@1"]["output"];
			readonly status: CodecTypes["pg/text@1"]["output"];
			readonly startedAt: CodecTypes["pg/int8@1"]["output"];
			readonly finishedAt: CodecTypes["pg/int8@1"]["output"] | null;
			readonly error: CodecTypes["pg/text@1"]["output"] | null;
			readonly errorCode: CodecTypes["pg/text@1"]["output"] | null;
			readonly usage: CodecTypes["pg/jsonb@1"]["output"] | null;
			readonly sandboxKey: CodecTypes["pg/text@1"]["output"] | null;
			readonly detachedSince: CodecTypes["pg/int8@1"]["output"] | null;
			readonly cancelRequested: CodecTypes["pg/bool@1"]["output"] | null;
			readonly driverEpoch: CodecTypes["pg/int4@1"]["output"] | null;
		};
		readonly ChatThread: {
			readonly threadId: CodecTypes["pg/text@1"]["output"];
			readonly messages: CodecTypes["pg/jsonb@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly CodeAgentSession: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly ownerId: CodecTypes["pg/uuid@1"]["output"];
			readonly title: CodecTypes["pg/text@1"]["output"];
			readonly workspacePath: CodecTypes["pg/text@1"]["output"];
			readonly endpointId: CodecTypes["pg/uuid@1"]["output"];
			readonly harness: CodecTypes["pg/text@1"]["output"];
			readonly model: CodecTypes["pg/text@1"]["output"];
			readonly approvedCommands: CodecTypes["pg/jsonb@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly Conversation: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly ownerId: CodecTypes["pg/uuid@1"]["output"];
			readonly title: CodecTypes["pg/text@1"]["output"];
			readonly endpointId: CodecTypes["pg/uuid@1"]["output"] | null;
			readonly model: CodecTypes["pg/text@1"]["output"] | null;
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly Endpoint: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly name: CodecTypes["pg/text@1"]["output"];
			readonly url: CodecTypes["pg/text@1"]["output"];
			readonly apiKeyEncrypted: CodecTypes["pg/text@1"]["output"] | null;
			readonly provider: CodecTypes["pg/text@1"]["output"];
			readonly options: CodecTypes["pg/jsonb@1"]["output"] | null;
			readonly ownerId: CodecTypes["pg/uuid@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly discovered: CodecTypes["pg/bool@1"]["output"] | null;
		};
		readonly Memory: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly text: CodecTypes["pg/text@1"]["output"];
			readonly category: CodecTypes["pg/text@1"]["output"];
			readonly source: CodecTypes["pg/text@1"]["output"];
			readonly ownerId: CodecTypes["pg/uuid@1"]["output"];
		};
		readonly ModelSetting: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly endpointId: CodecTypes["pg/uuid@1"]["output"];
			readonly model: CodecTypes["pg/text@1"]["output"];
			readonly options: CodecTypes["pg/jsonb@1"]["output"] | null;
			readonly ownerId: CodecTypes["pg/uuid@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly Session: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly expiresAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly token: CodecTypes["pg/text@1"]["output"];
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly ipAddress: CodecTypes["pg/text@1"]["output"] | null;
			readonly userAgent: CodecTypes["pg/text@1"]["output"] | null;
			readonly userId: CodecTypes["pg/uuid@1"]["output"];
		};
		readonly User: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly name: CodecTypes["pg/text@1"]["output"];
			readonly email: CodecTypes["pg/text@1"]["output"];
			readonly emailVerified: CodecTypes["pg/bool@1"]["output"];
			readonly image: CodecTypes["pg/text@1"]["output"] | null;
			readonly systemPrompt: CodecTypes["pg/text@1"]["output"] | null;
			readonly temperature: CodecTypes["pg/float8@1"]["output"] | null;
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly Verification: {
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly identifier: CodecTypes["pg/text@1"]["output"];
			readonly value: CodecTypes["pg/text@1"]["output"];
			readonly expiresAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
	};
};
export type FieldInputTypes = {
	readonly public: {
		readonly Account: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly issuer: CodecTypes["pg/text@1"]["input"];
			readonly accountId: CodecTypes["pg/text@1"]["input"];
			readonly providerId: CodecTypes["pg/text@1"]["input"];
			readonly userId: CodecTypes["pg/uuid@1"]["input"];
			readonly accessToken: CodecTypes["pg/text@1"]["input"] | null;
			readonly refreshToken: CodecTypes["pg/text@1"]["input"] | null;
			readonly idToken: CodecTypes["pg/text@1"]["input"] | null;
			readonly accessTokenExpiresAt: CodecTypes["pg/timestamp-temporal@1"]["input"] | null;
			readonly refreshTokenExpiresAt: CodecTypes["pg/timestamp-temporal@1"]["input"] | null;
			readonly scope: CodecTypes["pg/text@1"]["input"] | null;
			readonly password: CodecTypes["pg/text@1"]["input"] | null;
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly ChatInterrupt: {
			readonly interruptId: CodecTypes["pg/text@1"]["input"];
			readonly runId: CodecTypes["pg/text@1"]["input"];
			readonly threadId: CodecTypes["pg/text@1"]["input"];
			readonly status: CodecTypes["pg/text@1"]["input"];
			readonly requestedAt: CodecTypes["pg/int8@1"]["input"];
			readonly resolvedAt: CodecTypes["pg/int8@1"]["input"] | null;
			readonly payload: CodecTypes["pg/jsonb@1"]["input"];
			readonly response: CodecTypes["pg/jsonb@1"]["input"] | null;
		};
		readonly ChatRun: {
			readonly runId: CodecTypes["pg/text@1"]["input"];
			readonly threadId: CodecTypes["pg/text@1"]["input"];
			readonly status: CodecTypes["pg/text@1"]["input"];
			readonly startedAt: CodecTypes["pg/int8@1"]["input"];
			readonly finishedAt: CodecTypes["pg/int8@1"]["input"] | null;
			readonly error: CodecTypes["pg/text@1"]["input"] | null;
			readonly errorCode: CodecTypes["pg/text@1"]["input"] | null;
			readonly usage: CodecTypes["pg/jsonb@1"]["input"] | null;
			readonly sandboxKey: CodecTypes["pg/text@1"]["input"] | null;
			readonly detachedSince: CodecTypes["pg/int8@1"]["input"] | null;
			readonly cancelRequested: CodecTypes["pg/bool@1"]["input"] | null;
			readonly driverEpoch: CodecTypes["pg/int4@1"]["input"] | null;
		};
		readonly ChatThread: {
			readonly threadId: CodecTypes["pg/text@1"]["input"];
			readonly messages: CodecTypes["pg/jsonb@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly CodeAgentSession: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly ownerId: CodecTypes["pg/uuid@1"]["input"];
			readonly title: CodecTypes["pg/text@1"]["input"];
			readonly workspacePath: CodecTypes["pg/text@1"]["input"];
			readonly endpointId: CodecTypes["pg/uuid@1"]["input"];
			readonly harness: CodecTypes["pg/text@1"]["input"];
			readonly model: CodecTypes["pg/text@1"]["input"];
			readonly approvedCommands: CodecTypes["pg/jsonb@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly Conversation: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly ownerId: CodecTypes["pg/uuid@1"]["input"];
			readonly title: CodecTypes["pg/text@1"]["input"];
			readonly endpointId: CodecTypes["pg/uuid@1"]["input"] | null;
			readonly model: CodecTypes["pg/text@1"]["input"] | null;
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly Endpoint: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly name: CodecTypes["pg/text@1"]["input"];
			readonly url: CodecTypes["pg/text@1"]["input"];
			readonly apiKeyEncrypted: CodecTypes["pg/text@1"]["input"] | null;
			readonly provider: CodecTypes["pg/text@1"]["input"];
			readonly options: CodecTypes["pg/jsonb@1"]["input"] | null;
			readonly ownerId: CodecTypes["pg/uuid@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly discovered: CodecTypes["pg/bool@1"]["input"] | null;
		};
		readonly Memory: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly text: CodecTypes["pg/text@1"]["input"];
			readonly category: CodecTypes["pg/text@1"]["input"];
			readonly source: CodecTypes["pg/text@1"]["input"];
			readonly ownerId: CodecTypes["pg/uuid@1"]["input"];
		};
		readonly ModelSetting: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly endpointId: CodecTypes["pg/uuid@1"]["input"];
			readonly model: CodecTypes["pg/text@1"]["input"];
			readonly options: CodecTypes["pg/jsonb@1"]["input"] | null;
			readonly ownerId: CodecTypes["pg/uuid@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly Session: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly expiresAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly token: CodecTypes["pg/text@1"]["input"];
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly ipAddress: CodecTypes["pg/text@1"]["input"] | null;
			readonly userAgent: CodecTypes["pg/text@1"]["input"] | null;
			readonly userId: CodecTypes["pg/uuid@1"]["input"];
		};
		readonly User: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly name: CodecTypes["pg/text@1"]["input"];
			readonly email: CodecTypes["pg/text@1"]["input"];
			readonly emailVerified: CodecTypes["pg/bool@1"]["input"];
			readonly image: CodecTypes["pg/text@1"]["input"] | null;
			readonly systemPrompt: CodecTypes["pg/text@1"]["input"] | null;
			readonly temperature: CodecTypes["pg/float8@1"]["input"] | null;
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly Verification: {
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly identifier: CodecTypes["pg/text@1"]["input"];
			readonly value: CodecTypes["pg/text@1"]["input"];
			readonly expiresAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly createdAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly updatedAt: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
	};
};
export type StorageColumnTypes = {
	readonly public: {
		readonly account: {
			readonly access_token: CodecTypes["pg/text@1"]["output"] | null;
			readonly access_token_expires_at: CodecTypes["pg/timestamp-temporal@1"]["output"] | null;
			readonly account_id: CodecTypes["pg/text@1"]["output"];
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly id_token: CodecTypes["pg/text@1"]["output"] | null;
			readonly issuer: CodecTypes["pg/text@1"]["output"];
			readonly password: CodecTypes["pg/text@1"]["output"] | null;
			readonly provider_id: CodecTypes["pg/text@1"]["output"];
			readonly refresh_token: CodecTypes["pg/text@1"]["output"] | null;
			readonly refresh_token_expires_at: CodecTypes["pg/timestamp-temporal@1"]["output"] | null;
			readonly scope: CodecTypes["pg/text@1"]["output"] | null;
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly user_id: CodecTypes["pg/uuid@1"]["output"];
		};
		readonly chat_interrupt: {
			readonly interrupt_id: CodecTypes["pg/text@1"]["output"];
			readonly payload: CodecTypes["pg/jsonb@1"]["output"];
			readonly requested_at: CodecTypes["pg/int8@1"]["output"];
			readonly resolved_at: CodecTypes["pg/int8@1"]["output"] | null;
			readonly response: CodecTypes["pg/jsonb@1"]["output"] | null;
			readonly run_id: CodecTypes["pg/text@1"]["output"];
			readonly status: CodecTypes["pg/text@1"]["output"];
			readonly thread_id: CodecTypes["pg/text@1"]["output"];
		};
		readonly chat_run: {
			readonly cancel_requested: CodecTypes["pg/bool@1"]["output"] | null;
			readonly detached_since: CodecTypes["pg/int8@1"]["output"] | null;
			readonly driver_epoch: CodecTypes["pg/int4@1"]["output"] | null;
			readonly error: CodecTypes["pg/text@1"]["output"] | null;
			readonly error_code: CodecTypes["pg/text@1"]["output"] | null;
			readonly finished_at: CodecTypes["pg/int8@1"]["output"] | null;
			readonly run_id: CodecTypes["pg/text@1"]["output"];
			readonly sandbox_key: CodecTypes["pg/text@1"]["output"] | null;
			readonly started_at: CodecTypes["pg/int8@1"]["output"];
			readonly status: CodecTypes["pg/text@1"]["output"];
			readonly thread_id: CodecTypes["pg/text@1"]["output"];
			readonly usage: CodecTypes["pg/jsonb@1"]["output"] | null;
		};
		readonly chat_thread: {
			readonly messages: CodecTypes["pg/jsonb@1"]["output"];
			readonly thread_id: CodecTypes["pg/text@1"]["output"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly code_agent_session: {
			readonly approved_commands: CodecTypes["pg/jsonb@1"]["output"];
			readonly endpoint_id: CodecTypes["pg/uuid@1"]["output"];
			readonly harness: CodecTypes["pg/text@1"]["output"];
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly model: CodecTypes["pg/text@1"]["output"];
			readonly owner_id: CodecTypes["pg/uuid@1"]["output"];
			readonly title: CodecTypes["pg/text@1"]["output"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly workspace_path: CodecTypes["pg/text@1"]["output"];
		};
		readonly conversation: {
			readonly endpoint_id: CodecTypes["pg/uuid@1"]["output"] | null;
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly model: CodecTypes["pg/text@1"]["output"] | null;
			readonly owner_id: CodecTypes["pg/uuid@1"]["output"];
			readonly title: CodecTypes["pg/text@1"]["output"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly endpoint: {
			readonly api_key_encrypted: CodecTypes["pg/text@1"]["output"] | null;
			readonly discovered: CodecTypes["pg/bool@1"]["output"] | null;
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly name: CodecTypes["pg/text@1"]["output"];
			readonly options: CodecTypes["pg/jsonb@1"]["output"] | null;
			readonly owner_id: CodecTypes["pg/uuid@1"]["output"];
			readonly provider: CodecTypes["pg/text@1"]["output"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly url: CodecTypes["pg/text@1"]["output"];
		};
		readonly memory: {
			readonly category: CodecTypes["pg/text@1"]["output"];
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly owner_id: CodecTypes["pg/uuid@1"]["output"];
			readonly source: CodecTypes["pg/text@1"]["output"];
			readonly text: CodecTypes["pg/text@1"]["output"];
		};
		readonly model_setting: {
			readonly endpoint_id: CodecTypes["pg/uuid@1"]["output"];
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly model: CodecTypes["pg/text@1"]["output"];
			readonly options: CodecTypes["pg/jsonb@1"]["output"] | null;
			readonly owner_id: CodecTypes["pg/uuid@1"]["output"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly session: {
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly expires_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly ip_address: CodecTypes["pg/text@1"]["output"] | null;
			readonly token: CodecTypes["pg/text@1"]["output"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly user_agent: CodecTypes["pg/text@1"]["output"] | null;
			readonly user_id: CodecTypes["pg/uuid@1"]["output"];
		};
		readonly user: {
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly email: CodecTypes["pg/text@1"]["output"];
			readonly email_verified: CodecTypes["pg/bool@1"]["output"];
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly image: CodecTypes["pg/text@1"]["output"] | null;
			readonly name: CodecTypes["pg/text@1"]["output"];
			readonly system_prompt: CodecTypes["pg/text@1"]["output"] | null;
			readonly temperature: CodecTypes["pg/float8@1"]["output"] | null;
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
		};
		readonly verification: {
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly expires_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly id: CodecTypes["pg/uuid@1"]["output"];
			readonly identifier: CodecTypes["pg/text@1"]["output"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["output"];
			readonly value: CodecTypes["pg/text@1"]["output"];
		};
	};
};
export type StorageColumnInputTypes = {
	readonly public: {
		readonly account: {
			readonly access_token: CodecTypes["pg/text@1"]["input"] | null;
			readonly access_token_expires_at: CodecTypes["pg/timestamp-temporal@1"]["input"] | null;
			readonly account_id: CodecTypes["pg/text@1"]["input"];
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly id_token: CodecTypes["pg/text@1"]["input"] | null;
			readonly issuer: CodecTypes["pg/text@1"]["input"];
			readonly password: CodecTypes["pg/text@1"]["input"] | null;
			readonly provider_id: CodecTypes["pg/text@1"]["input"];
			readonly refresh_token: CodecTypes["pg/text@1"]["input"] | null;
			readonly refresh_token_expires_at: CodecTypes["pg/timestamp-temporal@1"]["input"] | null;
			readonly scope: CodecTypes["pg/text@1"]["input"] | null;
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly user_id: CodecTypes["pg/uuid@1"]["input"];
		};
		readonly chat_interrupt: {
			readonly interrupt_id: CodecTypes["pg/text@1"]["input"];
			readonly payload: CodecTypes["pg/jsonb@1"]["input"];
			readonly requested_at: CodecTypes["pg/int8@1"]["input"];
			readonly resolved_at: CodecTypes["pg/int8@1"]["input"] | null;
			readonly response: CodecTypes["pg/jsonb@1"]["input"] | null;
			readonly run_id: CodecTypes["pg/text@1"]["input"];
			readonly status: CodecTypes["pg/text@1"]["input"];
			readonly thread_id: CodecTypes["pg/text@1"]["input"];
		};
		readonly chat_run: {
			readonly cancel_requested: CodecTypes["pg/bool@1"]["input"] | null;
			readonly detached_since: CodecTypes["pg/int8@1"]["input"] | null;
			readonly driver_epoch: CodecTypes["pg/int4@1"]["input"] | null;
			readonly error: CodecTypes["pg/text@1"]["input"] | null;
			readonly error_code: CodecTypes["pg/text@1"]["input"] | null;
			readonly finished_at: CodecTypes["pg/int8@1"]["input"] | null;
			readonly run_id: CodecTypes["pg/text@1"]["input"];
			readonly sandbox_key: CodecTypes["pg/text@1"]["input"] | null;
			readonly started_at: CodecTypes["pg/int8@1"]["input"];
			readonly status: CodecTypes["pg/text@1"]["input"];
			readonly thread_id: CodecTypes["pg/text@1"]["input"];
			readonly usage: CodecTypes["pg/jsonb@1"]["input"] | null;
		};
		readonly chat_thread: {
			readonly messages: CodecTypes["pg/jsonb@1"]["input"];
			readonly thread_id: CodecTypes["pg/text@1"]["input"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly code_agent_session: {
			readonly approved_commands: CodecTypes["pg/jsonb@1"]["input"];
			readonly endpoint_id: CodecTypes["pg/uuid@1"]["input"];
			readonly harness: CodecTypes["pg/text@1"]["input"];
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly model: CodecTypes["pg/text@1"]["input"];
			readonly owner_id: CodecTypes["pg/uuid@1"]["input"];
			readonly title: CodecTypes["pg/text@1"]["input"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly workspace_path: CodecTypes["pg/text@1"]["input"];
		};
		readonly conversation: {
			readonly endpoint_id: CodecTypes["pg/uuid@1"]["input"] | null;
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly model: CodecTypes["pg/text@1"]["input"] | null;
			readonly owner_id: CodecTypes["pg/uuid@1"]["input"];
			readonly title: CodecTypes["pg/text@1"]["input"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly endpoint: {
			readonly api_key_encrypted: CodecTypes["pg/text@1"]["input"] | null;
			readonly discovered: CodecTypes["pg/bool@1"]["input"] | null;
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly name: CodecTypes["pg/text@1"]["input"];
			readonly options: CodecTypes["pg/jsonb@1"]["input"] | null;
			readonly owner_id: CodecTypes["pg/uuid@1"]["input"];
			readonly provider: CodecTypes["pg/text@1"]["input"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly url: CodecTypes["pg/text@1"]["input"];
		};
		readonly memory: {
			readonly category: CodecTypes["pg/text@1"]["input"];
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly owner_id: CodecTypes["pg/uuid@1"]["input"];
			readonly source: CodecTypes["pg/text@1"]["input"];
			readonly text: CodecTypes["pg/text@1"]["input"];
		};
		readonly model_setting: {
			readonly endpoint_id: CodecTypes["pg/uuid@1"]["input"];
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly model: CodecTypes["pg/text@1"]["input"];
			readonly options: CodecTypes["pg/jsonb@1"]["input"] | null;
			readonly owner_id: CodecTypes["pg/uuid@1"]["input"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly session: {
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly expires_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly ip_address: CodecTypes["pg/text@1"]["input"] | null;
			readonly token: CodecTypes["pg/text@1"]["input"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly user_agent: CodecTypes["pg/text@1"]["input"] | null;
			readonly user_id: CodecTypes["pg/uuid@1"]["input"];
		};
		readonly user: {
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly email: CodecTypes["pg/text@1"]["input"];
			readonly email_verified: CodecTypes["pg/bool@1"]["input"];
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly image: CodecTypes["pg/text@1"]["input"] | null;
			readonly name: CodecTypes["pg/text@1"]["input"];
			readonly system_prompt: CodecTypes["pg/text@1"]["input"] | null;
			readonly temperature: CodecTypes["pg/float8@1"]["input"] | null;
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
		};
		readonly verification: {
			readonly created_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly expires_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly id: CodecTypes["pg/uuid@1"]["input"];
			readonly identifier: CodecTypes["pg/text@1"]["input"];
			readonly updated_at: CodecTypes["pg/timestamp-temporal@1"]["input"];
			readonly value: CodecTypes["pg/text@1"]["input"];
		};
	};
};
export type TypeMaps = TypeMapsType<
	CodecTypes,
	QueryOperationTypes,
	FieldOutputTypes,
	FieldInputTypes,
	StorageColumnTypes,
	StorageColumnInputTypes,
	AggregateTypes
>;

type ContractBase = Omit<
	ContractType<{
		readonly namespaces: {
			readonly public: {
				readonly id: "public";
				readonly kind: "postgres-schema";
				readonly entries: {
					readonly table: {
						readonly account: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly issuer: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly account_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly provider_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly user_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly access_token: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly refresh_token: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly id_token: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly access_token_expires_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: true;
									readonly typeParams: { readonly precision: 3 };
								};
								readonly refresh_token_expires_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: true;
									readonly typeParams: { readonly precision: 3 };
								};
								readonly scope: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly password: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly created_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly default: { readonly kind: "function"; readonly expression: "now()" };
									readonly typeParams: { readonly precision: 3 };
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "account_issuer_accountId_uidx";
									readonly columns: readonly ["issuer", "account_id"];
									readonly unique: true;
								},
								{
									readonly name: "account_user_id_idx";
									readonly columns: readonly ["user_id"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "account";
										readonly columns: readonly ["user_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "user";
										readonly columns: readonly ["id"];
									};
								},
							];
						};
						readonly chat_interrupt: {
							columns: {
								readonly interrupt_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly run_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly thread_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly status: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly requested_at: {
									readonly nativeType: "int8";
									readonly codecId: "pg/int8@1";
									readonly nullable: false;
								};
								readonly resolved_at: {
									readonly nativeType: "int8";
									readonly codecId: "pg/int8@1";
									readonly nullable: true;
								};
								readonly payload: {
									readonly nativeType: "jsonb";
									readonly codecId: "pg/jsonb@1";
									readonly nullable: false;
								};
								readonly response: {
									readonly nativeType: "jsonb";
									readonly codecId: "pg/jsonb@1";
									readonly nullable: true;
								};
							};
							primaryKey: { readonly columns: readonly ["interrupt_id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "chat_interrupt_thread_id_requested_at_idx";
									readonly columns: readonly ["thread_id", "requested_at"];
									readonly unique: false;
								},
								{
									readonly name: "chat_interrupt_run_id_requested_at_idx";
									readonly columns: readonly ["run_id", "requested_at"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [];
						};
						readonly chat_run: {
							columns: {
								readonly run_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly thread_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly status: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly started_at: {
									readonly nativeType: "int8";
									readonly codecId: "pg/int8@1";
									readonly nullable: false;
								};
								readonly finished_at: {
									readonly nativeType: "int8";
									readonly codecId: "pg/int8@1";
									readonly nullable: true;
								};
								readonly error: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly error_code: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly usage: {
									readonly nativeType: "jsonb";
									readonly codecId: "pg/jsonb@1";
									readonly nullable: true;
								};
								readonly sandbox_key: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly detached_since: {
									readonly nativeType: "int8";
									readonly codecId: "pg/int8@1";
									readonly nullable: true;
								};
								readonly cancel_requested: {
									readonly nativeType: "bool";
									readonly codecId: "pg/bool@1";
									readonly nullable: true;
								};
								readonly driver_epoch: {
									readonly nativeType: "int4";
									readonly codecId: "pg/int4@1";
									readonly nullable: true;
								};
							};
							primaryKey: { readonly columns: readonly ["run_id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "chat_run_thread_id_status_idx";
									readonly columns: readonly ["thread_id", "status"];
									readonly unique: false;
								},
								{
									readonly name: "chat_run_thread_id_started_at_idx";
									readonly columns: readonly ["thread_id", "started_at"];
									readonly unique: false;
								},
								{
									readonly name: "chat_run_status_detached_since_idx";
									readonly columns: readonly ["status", "detached_since"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [];
						};
						readonly chat_thread: {
							columns: {
								readonly thread_id: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly messages: {
									readonly nativeType: "jsonb";
									readonly codecId: "pg/jsonb@1";
									readonly nullable: false;
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
							};
							primaryKey: { readonly columns: readonly ["thread_id"] };
							uniques: readonly [];
							indexes: readonly [];
							foreignKeys: readonly [];
						};
						readonly code_agent_session: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly owner_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly title: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly workspace_path: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly endpoint_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly harness: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly model: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly approved_commands: {
									readonly nativeType: "jsonb";
									readonly codecId: "pg/jsonb@1";
									readonly nullable: false;
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "code_agent_session_owner_id_idx";
									readonly columns: readonly ["owner_id"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "code_agent_session";
										readonly columns: readonly ["owner_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "user";
										readonly columns: readonly ["id"];
									};
								},
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "code_agent_session";
										readonly columns: readonly ["endpoint_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "endpoint";
										readonly columns: readonly ["id"];
									};
								},
							];
						};
						readonly conversation: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly owner_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly title: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
									readonly default: {
										readonly kind: "literal";
										readonly value: DefaultLiteralValue<"pg/text@1", "New Chat">;
									};
								};
								readonly endpoint_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: true;
								};
								readonly model: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "conversation_owner_id_idx";
									readonly columns: readonly ["owner_id"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "conversation";
										readonly columns: readonly ["owner_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "user";
										readonly columns: readonly ["id"];
									};
								},
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "conversation";
										readonly columns: readonly ["endpoint_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "endpoint";
										readonly columns: readonly ["id"];
									};
								},
							];
						};
						readonly endpoint: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly name: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly url: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly api_key_encrypted: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly provider: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
									readonly default: {
										readonly kind: "literal";
										readonly value: DefaultLiteralValue<"pg/text@1", "openai">;
									};
								};
								readonly options: {
									readonly nativeType: "jsonb";
									readonly codecId: "pg/jsonb@1";
									readonly nullable: true;
								};
								readonly owner_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
								readonly discovered: {
									readonly nativeType: "bool";
									readonly codecId: "pg/bool@1";
									readonly nullable: true;
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "endpoint_owner_id_discovered_key";
									readonly columns: readonly ["owner_id", "discovered"];
									readonly unique: true;
								},
								{
									readonly name: "endpoint_owner_id_idx";
									readonly columns: readonly ["owner_id"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "endpoint";
										readonly columns: readonly ["owner_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "user";
										readonly columns: readonly ["id"];
									};
								},
							];
						};
						readonly memory: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly text: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly category: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
									readonly default: {
										readonly kind: "literal";
										readonly value: DefaultLiteralValue<"pg/text@1", "fact">;
									};
								};
								readonly source: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
									readonly default: {
										readonly kind: "literal";
										readonly value: DefaultLiteralValue<"pg/text@1", "user">;
									};
								};
								readonly owner_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "memory_owner_id_idx";
									readonly columns: readonly ["owner_id"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "memory";
										readonly columns: readonly ["owner_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "user";
										readonly columns: readonly ["id"];
									};
								},
							];
						};
						readonly model_setting: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly endpoint_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly model: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly options: {
									readonly nativeType: "jsonb";
									readonly codecId: "pg/jsonb@1";
									readonly nullable: true;
								};
								readonly owner_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "model_setting_endpoint_id_model_key";
									readonly columns: readonly ["endpoint_id", "model"];
									readonly unique: true;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "model_setting";
										readonly columns: readonly ["endpoint_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "endpoint";
										readonly columns: readonly ["id"];
									};
								},
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "model_setting";
										readonly columns: readonly ["owner_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "user";
										readonly columns: readonly ["id"];
									};
								},
							];
						};
						readonly session: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly expires_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
								readonly token: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly created_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly default: { readonly kind: "function"; readonly expression: "now()" };
									readonly typeParams: { readonly precision: 3 };
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
								readonly ip_address: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly user_agent: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly user_id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "session_token_key";
									readonly columns: readonly ["token"];
									readonly unique: true;
								},
								{
									readonly name: "session_user_id_idx";
									readonly columns: readonly ["user_id"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "session";
										readonly columns: readonly ["user_id"];
									};
									readonly target: {
										readonly namespaceId: "public" & NamespaceId;
										readonly tableName: "user";
										readonly columns: readonly ["id"];
									};
								},
							];
						};
						readonly user: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly name: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly email: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly email_verified: {
									readonly nativeType: "bool";
									readonly codecId: "pg/bool@1";
									readonly nullable: false;
									readonly default: {
										readonly kind: "literal";
										readonly value: DefaultLiteralValue<"pg/bool@1", false>;
									};
								};
								readonly image: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly system_prompt: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: true;
								};
								readonly temperature: {
									readonly nativeType: "float8";
									readonly codecId: "pg/float8@1";
									readonly nullable: true;
								};
								readonly created_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly default: { readonly kind: "function"; readonly expression: "now()" };
									readonly typeParams: { readonly precision: 3 };
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "user_email_key";
									readonly columns: readonly ["email"];
									readonly unique: true;
								},
							];
							foreignKeys: readonly [];
						};
						readonly verification: {
							columns: {
								readonly id: {
									readonly nativeType: "uuid";
									readonly codecId: "pg/uuid@1";
									readonly nullable: false;
								};
								readonly identifier: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly value: {
									readonly nativeType: "text";
									readonly codecId: "pg/text@1";
									readonly nullable: false;
								};
								readonly expires_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
								readonly created_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly default: { readonly kind: "function"; readonly expression: "now()" };
									readonly typeParams: { readonly precision: 3 };
								};
								readonly updated_at: {
									readonly nativeType: "timestamp";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly nullable: false;
									readonly typeParams: { readonly precision: 3 };
								};
							};
							primaryKey: { readonly columns: readonly ["id"] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: "verification_identifier_idx";
									readonly columns: readonly ["identifier"];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [];
						};
					};
				};
			};
		};
		readonly storageHash: StorageHash;
	}>,
	"roots" | "domain"
> & {
	readonly target: "postgres";
	readonly targetFamily: "sql";
	readonly roots: {
		readonly user: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
		readonly session: { readonly namespace: "public" & NamespaceId; readonly model: "Session" };
		readonly account: { readonly namespace: "public" & NamespaceId; readonly model: "Account" };
		readonly verification: {
			readonly namespace: "public" & NamespaceId;
			readonly model: "Verification";
		};
		readonly endpoint: { readonly namespace: "public" & NamespaceId; readonly model: "Endpoint" };
		readonly conversation: {
			readonly namespace: "public" & NamespaceId;
			readonly model: "Conversation";
		};
		readonly memory: { readonly namespace: "public" & NamespaceId; readonly model: "Memory" };
		readonly model_setting: {
			readonly namespace: "public" & NamespaceId;
			readonly model: "ModelSetting";
		};
		readonly chat_thread: {
			readonly namespace: "public" & NamespaceId;
			readonly model: "ChatThread";
		};
		readonly chat_run: { readonly namespace: "public" & NamespaceId; readonly model: "ChatRun" };
		readonly chat_interrupt: {
			readonly namespace: "public" & NamespaceId;
			readonly model: "ChatInterrupt";
		};
		readonly code_agent_session: {
			readonly namespace: "public" & NamespaceId;
			readonly model: "CodeAgentSession";
		};
	};
	readonly domain: {
		readonly namespaces: {
			readonly public: {
				readonly models: {
					readonly Account: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly issuer: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly accountId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly providerId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly userId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly accessToken: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly refreshToken: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly idToken: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly accessTokenExpiresAt: {
								readonly nullable: true;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly refreshTokenExpiresAt: {
								readonly nullable: true;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly scope: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly password: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
						};
						readonly relations: {
							readonly user: {
								readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["userId"];
									readonly targetFields: readonly ["id"];
								};
							};
						};
						readonly storage: {
							readonly table: "account";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly issuer: { readonly column: "issuer" };
								readonly accountId: { readonly column: "account_id" };
								readonly providerId: { readonly column: "provider_id" };
								readonly userId: { readonly column: "user_id" };
								readonly accessToken: { readonly column: "access_token" };
								readonly refreshToken: { readonly column: "refresh_token" };
								readonly idToken: { readonly column: "id_token" };
								readonly accessTokenExpiresAt: { readonly column: "access_token_expires_at" };
								readonly refreshTokenExpiresAt: { readonly column: "refresh_token_expires_at" };
								readonly scope: { readonly column: "scope" };
								readonly password: { readonly column: "password" };
								readonly createdAt: { readonly column: "created_at" };
								readonly updatedAt: { readonly column: "updated_at" };
							};
						};
					};
					readonly ChatInterrupt: {
						readonly fields: {
							readonly interruptId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly runId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly threadId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly status: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly requestedAt: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int8@1" };
							};
							readonly resolvedAt: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int8@1" };
							};
							readonly payload: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/jsonb@1" };
							};
							readonly response: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/jsonb@1" };
							};
						};
						readonly relations: Record<string, never>;
						readonly storage: {
							readonly table: "chat_interrupt";
							readonly namespaceId: "public";
							readonly fields: {
								readonly interruptId: { readonly column: "interrupt_id" };
								readonly runId: { readonly column: "run_id" };
								readonly threadId: { readonly column: "thread_id" };
								readonly status: { readonly column: "status" };
								readonly requestedAt: { readonly column: "requested_at" };
								readonly resolvedAt: { readonly column: "resolved_at" };
								readonly payload: { readonly column: "payload" };
								readonly response: { readonly column: "response" };
							};
						};
					};
					readonly ChatRun: {
						readonly fields: {
							readonly runId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly threadId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly status: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly startedAt: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int8@1" };
							};
							readonly finishedAt: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int8@1" };
							};
							readonly error: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly errorCode: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly usage: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/jsonb@1" };
							};
							readonly sandboxKey: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly detachedSince: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int8@1" };
							};
							readonly cancelRequested: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
							};
							readonly driverEpoch: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
							};
						};
						readonly relations: Record<string, never>;
						readonly storage: {
							readonly table: "chat_run";
							readonly namespaceId: "public";
							readonly fields: {
								readonly runId: { readonly column: "run_id" };
								readonly threadId: { readonly column: "thread_id" };
								readonly status: { readonly column: "status" };
								readonly startedAt: { readonly column: "started_at" };
								readonly finishedAt: { readonly column: "finished_at" };
								readonly error: { readonly column: "error" };
								readonly errorCode: { readonly column: "error_code" };
								readonly usage: { readonly column: "usage" };
								readonly sandboxKey: { readonly column: "sandbox_key" };
								readonly detachedSince: { readonly column: "detached_since" };
								readonly cancelRequested: { readonly column: "cancel_requested" };
								readonly driverEpoch: { readonly column: "driver_epoch" };
							};
						};
					};
					readonly ChatThread: {
						readonly fields: {
							readonly threadId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly messages: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/jsonb@1" };
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
						};
						readonly relations: Record<string, never>;
						readonly storage: {
							readonly table: "chat_thread";
							readonly namespaceId: "public";
							readonly fields: {
								readonly threadId: { readonly column: "thread_id" };
								readonly messages: { readonly column: "messages" };
								readonly updatedAt: { readonly column: "updated_at" };
							};
						};
					};
					readonly CodeAgentSession: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly ownerId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly title: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly workspacePath: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly endpointId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly harness: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly model: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly approvedCommands: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/jsonb@1" };
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
						};
						readonly relations: {
							readonly owner: {
								readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["ownerId"];
									readonly targetFields: readonly ["id"];
								};
							};
							readonly endpoint: {
								readonly to: {
									readonly namespace: "public" & NamespaceId;
									readonly model: "Endpoint";
								};
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["endpointId"];
									readonly targetFields: readonly ["id"];
								};
							};
						};
						readonly storage: {
							readonly table: "code_agent_session";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly ownerId: { readonly column: "owner_id" };
								readonly title: { readonly column: "title" };
								readonly workspacePath: { readonly column: "workspace_path" };
								readonly endpointId: { readonly column: "endpoint_id" };
								readonly harness: { readonly column: "harness" };
								readonly model: { readonly column: "model" };
								readonly approvedCommands: { readonly column: "approved_commands" };
								readonly updatedAt: { readonly column: "updated_at" };
							};
						};
					};
					readonly Conversation: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly ownerId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly title: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly endpointId: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly model: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
						};
						readonly relations: {
							readonly owner: {
								readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["ownerId"];
									readonly targetFields: readonly ["id"];
								};
							};
							readonly endpoint: {
								readonly to: {
									readonly namespace: "public" & NamespaceId;
									readonly model: "Endpoint";
								};
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["endpointId"];
									readonly targetFields: readonly ["id"];
								};
							};
						};
						readonly storage: {
							readonly table: "conversation";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly ownerId: { readonly column: "owner_id" };
								readonly title: { readonly column: "title" };
								readonly endpointId: { readonly column: "endpoint_id" };
								readonly model: { readonly column: "model" };
								readonly updatedAt: { readonly column: "updated_at" };
							};
						};
					};
					readonly Endpoint: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly name: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly url: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly apiKeyEncrypted: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly provider: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly options: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/jsonb@1" };
							};
							readonly ownerId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly discovered: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
							};
						};
						readonly relations: {
							readonly owner: {
								readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["ownerId"];
									readonly targetFields: readonly ["id"];
								};
							};
						};
						readonly storage: {
							readonly table: "endpoint";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly name: { readonly column: "name" };
								readonly url: { readonly column: "url" };
								readonly apiKeyEncrypted: { readonly column: "api_key_encrypted" };
								readonly provider: { readonly column: "provider" };
								readonly options: { readonly column: "options" };
								readonly ownerId: { readonly column: "owner_id" };
								readonly updatedAt: { readonly column: "updated_at" };
								readonly discovered: { readonly column: "discovered" };
							};
						};
					};
					readonly Memory: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly text: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly category: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly source: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly ownerId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
						};
						readonly relations: {
							readonly owner: {
								readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["ownerId"];
									readonly targetFields: readonly ["id"];
								};
							};
						};
						readonly storage: {
							readonly table: "memory";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly text: { readonly column: "text" };
								readonly category: { readonly column: "category" };
								readonly source: { readonly column: "source" };
								readonly ownerId: { readonly column: "owner_id" };
							};
						};
					};
					readonly ModelSetting: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly endpointId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly model: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly options: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/jsonb@1" };
							};
							readonly ownerId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
						};
						readonly relations: {
							readonly endpoint: {
								readonly to: {
									readonly namespace: "public" & NamespaceId;
									readonly model: "Endpoint";
								};
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["endpointId"];
									readonly targetFields: readonly ["id"];
								};
							};
							readonly owner: {
								readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["ownerId"];
									readonly targetFields: readonly ["id"];
								};
							};
						};
						readonly storage: {
							readonly table: "model_setting";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly endpointId: { readonly column: "endpoint_id" };
								readonly model: { readonly column: "model" };
								readonly options: { readonly column: "options" };
								readonly ownerId: { readonly column: "owner_id" };
								readonly updatedAt: { readonly column: "updated_at" };
							};
						};
					};
					readonly Session: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly expiresAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly token: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly ipAddress: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly userAgent: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly userId: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
						};
						readonly relations: {
							readonly user: {
								readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
								readonly cardinality: "N:1";
								readonly on: {
									readonly localFields: readonly ["userId"];
									readonly targetFields: readonly ["id"];
								};
							};
						};
						readonly storage: {
							readonly table: "session";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly expiresAt: { readonly column: "expires_at" };
								readonly token: { readonly column: "token" };
								readonly createdAt: { readonly column: "created_at" };
								readonly updatedAt: { readonly column: "updated_at" };
								readonly ipAddress: { readonly column: "ip_address" };
								readonly userAgent: { readonly column: "user_agent" };
								readonly userId: { readonly column: "user_id" };
							};
						};
					};
					readonly User: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly name: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly email: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly emailVerified: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
							};
							readonly image: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly systemPrompt: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly temperature: {
								readonly nullable: true;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/float8@1" };
							};
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
						};
						readonly relations: Record<string, never>;
						readonly storage: {
							readonly table: "user";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly name: { readonly column: "name" };
								readonly email: { readonly column: "email" };
								readonly emailVerified: { readonly column: "email_verified" };
								readonly image: { readonly column: "image" };
								readonly systemPrompt: { readonly column: "system_prompt" };
								readonly temperature: { readonly column: "temperature" };
								readonly createdAt: { readonly column: "created_at" };
								readonly updatedAt: { readonly column: "updated_at" };
							};
						};
					};
					readonly Verification: {
						readonly fields: {
							readonly id: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/uuid@1" };
							};
							readonly identifier: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly value: {
								readonly nullable: false;
								readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
							};
							readonly expiresAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: "scalar";
									readonly codecId: "pg/timestamp-temporal@1";
									readonly typeParams: { readonly precision: 3 };
								};
							};
						};
						readonly relations: Record<string, never>;
						readonly storage: {
							readonly table: "verification";
							readonly namespaceId: "public";
							readonly fields: {
								readonly id: { readonly column: "id" };
								readonly identifier: { readonly column: "identifier" };
								readonly value: { readonly column: "value" };
								readonly expiresAt: { readonly column: "expires_at" };
								readonly createdAt: { readonly column: "created_at" };
								readonly updatedAt: { readonly column: "updated_at" };
							};
						};
					};
				};
			};
		};
	};
	readonly capabilities: {
		readonly postgres: {
			readonly distinctOn: true;
			readonly jsonAgg: true;
			readonly lateral: true;
			readonly limit: true;
			readonly orderBy: true;
			readonly returning: true;
		};
		readonly sql: {
			readonly checkConstraint: true;
			readonly defaultInInsert: true;
			readonly enums: true;
			readonly lateral: true;
			readonly returning: true;
			readonly scalarList: true;
		};
	};
	readonly extensions: {};
	readonly execution: {
		readonly executionHash: ExecutionHash;
		readonly mutations: {
			readonly defaults: readonly [
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "account";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "code_agent_session";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "conversation";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "endpoint";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "memory";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "model_setting";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "session";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "user";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
				{
					readonly ref: {
						readonly namespace: "public";
						readonly table: "verification";
						readonly column: "id";
					};
					readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
				},
			];
		};
	};
	readonly meta: {};

	readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
